* Federated Explainability for Network Anomaly Characterization

This repository contains the source code and implementation of the
experiments described in the following paper:

Xabier Sáez-de-Cámara, Jose Luis Flores, Cristóbal Arellano, Aitor Urbieta, and Urko Zurutuza. 2023. Federated Explainability for Network Anomaly Characterization. In Proceedings of the 26th International Symposium on Research in Attacks, Intrusions and Defenses (RAID '23). Association for Computing Machinery, New York, NY, USA, 346–365. [[https://doi.org/10.1145/3607199.3607234][https://doi.org/10.1145/3607199.3607234]]

Open access from the conference website [[https://raid2023.org/accepted_open.html][https://raid2023.org/accepted_open.html]]

** Environment

Create the environment from the ~environment.yml~ file:

#+BEGIN_SRC bash
  conda env create -f environment.yml
#+END_SRC

Activate the environment with:

#+BEGIN_SRC bash
  conda activate flxai
#+END_SRC


** Dependencies

- This project uses [[https://github.com/xsaga/kfed-rounded][https://github.com/xsaga/kfed-rounded]] for the one-shot federated learning k-means implementation.
  It is a modified fork from the original implementation at [[https://github.com/metastableB/kfed][https://github.com/metastableB/kfed]]
  by [[https://proceedings.mlr.press/v139/dennis21a.html][Dennis, D. K., Li, T., & Smith, V. (2021, July). Heterogeneity for the win: One-shot federated clustering. In International Conference on Machine Learning (pp. 2611-2620). PMLR]].
- ~wget~ (optional)
- ~find~ (optional)
- ~7zip~ (optional)
